name: flutter_lab
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.0

scripts:
  doc: dart scripts/doc.dart

dependencies:
  flutter:
    sdk: flutter
  ui_router:
  flutter_riverpod:
  flutter_hooks:
  riverpod_annotation:
  freezed_annotation:
  google_sign_in:
  envied:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  json_serializable:
  riverpod_generator:
  freezed:
  envied_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
