// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQtFgf3DN5RYOOcSPVokqglzUU37EaUks',
    appId: '1:132329368813:web:f644a4e7f971ad5961f0e4',
    messagingSenderId: '132329368813',
    projectId: 'rbdog-flutter-lab',
    authDomain: 'rbdog-flutter-lab.firebaseapp.com',
    storageBucket: 'rbdog-flutter-lab.appspot.com',
    measurementId: 'G-52XLDPWDLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAldmVBeygsCHdL7qwCFERi-pofHeCdAsc',
    appId: '1:132329368813:android:26e4c1d4990fe18b61f0e4',
    messagingSenderId: '132329368813',
    projectId: 'rbdog-flutter-lab',
    storageBucket: 'rbdog-flutter-lab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUy6L1H8145m2DjCDkdJqLKYXqESkl7NE',
    appId: '1:132329368813:ios:cedf908caf99782b61f0e4',
    messagingSenderId: '132329368813',
    projectId: 'rbdog-flutter-lab',
    storageBucket: 'rbdog-flutter-lab.appspot.com',
    iosClientId: '132329368813-cpukq0bi1difb1l3vgsdpt366poo9q59.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLab',
  );
}
